### ISSUE TITLE
Tweakscale Message forces Game Halt

### ISSUE THREAD

**Issue by SkiRich** [net-lisias-ksp/TweakScale#117]
The new message on screen warning while loading all the assets about compatibility with the latest v1.10 saying.. save NOW yada yada, if you press OK forces the Game to Halt.
No where on the screen does it say it will do that.
It took me three shots to figure that out.
With 113 mods running that was 20 minutes of wasted time wondering what just happened.

You may want to modify that message to add something in it about the behavior, or at least give folks an option to exit or not.

**Comment by Lisias** [comment]
If you press Cancel, the Warning closes and the game keeps going.

![Screen Shot 2020-07-01 at 16 38 08](https://user-images.githubusercontent.com/64334/86284501-5ead9700-bbb9-11ea-88a2-49855794ddd1.png)

The OK closes the game by design - people usually does not read the text and just clicks OK, what can be dangerous - loading a savegame when something weird is detected can lead to corruption, and it's the reason the Houstons are coded this way,
