### ISSUE TITLE
Latest beta: size changes do not propagate to other parts in symmetry

### ISSUE THREAD

**Issue by AccidentalDisassembly** [net-lisias-ksp/TweakScale#144]
[Player.log](https://github.com/net-lisias-ksp/TweakScale/files/5324794/Player.log)
Always possible it's an interaction with other mods. Using latest TS beta, resizing a part placed in symmetry will not update the other parts in the symmetry group. If you pick up the part and re-place it, the others will update to the correct size. Appears not to be purely visual; Engineer reports different masses etc.
![image](https://user-images.githubusercontent.com/8712935/95032191-4600c180-067f-11eb-8f04-2d0a1454216e.png)

**Comment by Lisias** [comment]
Hi, @AccidentalDisassembly .

In order to keep some sanity on this insanity :P , problems related to a Beta release should be reported to an specific issue, as this is work in progress yet.

Problem - I forgot to state that on the Release page.

I "moved" the problem into the Issue #42 where development problems on TS Beta is handled, I'm fixing the Release Notes for the Beta Release, and I'm so closing this one to keep the back log more or less sane.

Thanks for the report!
