### ISSUE TITLE
Stock Solar Panel Animations

### ISSUE THREAD

**Issue by eberkain** [net-lisias-ksp/TweakScale#149]
Whenever I load up a vessel that has the boxed in solar panels that have been scaled up they appear to not be fully retracted. Deploying and retracting causes the anim to reset and look correct. 

![20201223191444_1](https://user-images.githubusercontent.com/2171616/103048341-eb775300-4553-11eb-808a-7f4170442e81.jpg)

**Comment by Lisias** [comment]
Yep, the problem happens with parts scaled up and down too....

![screenshot3](https://user-images.githubusercontent.com/64334/103072406-4173e700-45a4-11eb-9bbe-b4a07f6995b8.png)

![screenshot4](https://user-images.githubusercontent.com/64334/103072420-4a64b880-45a4-11eb-9416-3be25efe7ebf.png)

I'm somewhat puzzle, because TweakScale doesn't touch animations (other than scaling the meshes), and had TS made some mess on it, just deploying and retracting the part would not fix the misbehaviour...

Still looing on it....

**Comment by Lisias** [comment]
Hummm.... Non scaled parts are also being deployed with the misbehaviour....

![screenshot5](https://user-images.githubusercontent.com/64334/103072582-a0396080-45a4-11eb-94ff-1624146afa85.png)

**Comment by Lisias** [comment]
In order to save some CPU, TweakScale disables itself on unscaled parts (this helps a bit, as Update and FixedUpdate are not called when the module is disabled). So I don't think this is something on TweakScale.

So I fire up KSP 1.11 **without** TweakScale installed to see what I get:
![screenshot6](https://user-images.githubusercontent.com/64334/103073217-05418600-45a6-11eb-930f-4363a345a045.png)

The is the same vessel from the previous screenshots, inclusive already launched. Without TweakScale, any scaling is lost, and we got the same misbehaviour.

So I recovered the vessel and replaced the photovoltaic panels for fresh parts from the Parts Palette, so being absolutely sure that stock values are applied on them:
![screenshot7](https://user-images.githubusercontent.com/64334/103073620-b0523f80-45a6-11eb-92e9-51d9540107d6.png)

And yeah, same misbehaviour.

My guess is that Squad forgot to initialise the animation's control variable on launch.

This should be reported on the KSP's [bugtrack](https://bugs.kerbalspaceprogram.com). Feel free to link this Issue if you want!

Cheers!
