### ISSUE TITLE
Extra old .version file in SpaceDock download

### ISSUE THREAD

**Issue by HebaruSan** [net-lisias-ksp/TweakScale#16]
The [download for 2.4.0.7](https://spacedock.info/mod/127/TweakScale/download/2.4.0.7) contains an extra .version file at `GameData/TweakScale/TweakScale-Experimental.version`, with some wrong metadata:

```json
	"VERSION":{
		"MAJOR":2,
		"MINOR":4,
		"PATCH":0,
		"BUILD":6
		},
```

This is currently stopping the CKAN bot from indexing this version.

**Comment by Lisias** [comment]
Thanks for the heads up. Mangling with my building process while drinking beer on the new year's festivities was not exactly the best of ideas.

Such mistake were leaked to SpaceDock and CurseForge too (the netkan should be fetching files from GITHUIB, at least it was I set it up).

Fixed in all three places.

**Comment by HebaruSan** [comment]
> the netkan should be fetching files from GITHUIB, at least it was I set it up

Your pull request switched it to SD:

https://github.com/KSP-CKAN/NetKAN/pull/6798/files#diff-e01156885f9b41bad2e838da5bc62142R3

Either way is fine, really, but just an FYI in case you *really* want it to pull from GitHub.

**Comment by Lisias** [comment]
Ouch… I forgot I did that. Need to switch my coffee, this brand is not working.

Let's stay this way. I will handle SpaceDock as "THE" Distribution site from nowadays (and fix again my building scripts)
