### ISSUE TITLE
Two white buttons

### ISSUE THREAD

**Issue by K0smonaute0** [net-lisias-ksp/TweakScale#164]
Welp , i downloaded the mod and placed it in my gamedata folder but when right-click on a parts i dont see the line where you can  chose the perfect size , i only have two white buttons , the left one for a bigger size and the right one for smaller , but when i click them the size is way way more bigger than beffore , i can't make it a little more big so i can't do my ship's with a good size , do i do something wrong ? (ps : i got the game in 1.8.0)
![Capture](https://user-images.githubusercontent.com/78687991/107147172-e7a95f80-694c-11eb-84cb-8e27769c8496.PNG)

**Comment by Lisias** [comment]
KSP 1.8.0 has a bug (something not initialised on the prefab) that broke a lot of add'ons, TweakScale included.

That missing initialisation causes exactly what you are seeing, a widget on the PAW not being drawn.

KSP 1.8.1 had it fixed.

Since 1.8.0 had a short life, I didn't bored to code a fix for it using KSP Recall (so everybody would had it fixed, and not only TweakScale).

There's any reason you can't use KSP 1.8.1 ? KSP 1.8.0 is terribly buggy!

**Comment by Lisias** [comment]
Details about this problem can be found [here on Forum](https://forum.kerbalspaceprogram.com/index.php?/topic/7542-the-official-unoffical-quothelp-a-fellow-plugin-developerquot-thread/&do=findComment&comment=3691920).

**Comment by Lisias** [comment]
Since the user didn't bothered to answer back, I'm closing this.
