### ISSUE TITLE
fatal showstopper errors on startup 

### ISSUE THREAD

**Issue by DannyDorito420** [net-lisias-ksp/TweakScale#189]
upon opening my game with tweakscale installed it gives me a popup saying: "houston we have a problem, unfortunately tweakscale has found 27 FATAL issues on your ksp installment!". 

The error popup:
![tweakscale problem](https://user-images.githubusercontent.com/88232092/127736423-f4cffe26-31ff-42e5-82a9-5722088ab00a.png)

my gamedata folder:
![File Explorer 31_07_2021 11_04_24](https://user-images.githubusercontent.com/88232092/127736437-4c89b428-ea91-4741-bfbe-d164b6a9c1a9.png)
![File Explorer 31_07_2021 11_04_18](https://user-images.githubusercontent.com/88232092/127736435-50b108c7-8ddb-42e0-b718-e585056be236.png)

My ksp error log:
![KSP - Notepad 31_07_2021 11_06_22](https://user-images.githubusercontent.com/88232092/127736474-104d292b-2ba7-487f-8bfd-cfe33873cc02.png)

**Comment by Lisias** [comment]
Hi. Usually I need the **full** KSP.log file, otherwise I can't help. Knowingly that a part is broken is only part of the problem, I need to know who patched them in order to diagnose the problem. 

However,  I recognized some parts from the great Large Shipt Parts mod from SpannerMonkey.  :).

So I know the fix. Install TweakScale Companion for SMCE. I have a lot of patches fixed on it.

https://github.com/net-lisias-ksp/TweakScaleCompanion_SMCE/releases

**Comment by Lisias** [comment]
Let me know if it fixed your problem so I can close this.

Cheers?

**Comment by DannyDorito420** [comment]
Thank you this fixed the problem. i will close the issue now
