### ISSUE TITLE
Eorror

### ISSUE THREAD

**Issue by Connorray1234** [net-lisias-ksp/TweakScale#205]
Its saying its installed wrong but i know it isnt becasue it didnt error in 1.11.2 i used ckan to install its saying it on during loading for 1.12
i know its installed right i tried downloading one from the fourms but it still gave me the message 
is this kind of issue known?
![Screenshot_756](https://user-images.githubusercontent.com/85777151/138185405-423a9ee4-3730-4b37-9d9c-5c733d68a695.jpg)
I wanna say this one is relavent too?

![Screenshot_754](https://user-images.githubusercontent.com/85777151/138187663-1ca021cf-d932-425c-9856-b230b5962ed6.jpg)

am not entirely sure aboot scale redist 999 blah
i checked there aint is more then two 999 in there theres one!

**Comment by Lisias** [comment]
Hi, @Connorray1234 .

Did my last post fixed your problem?

Cheers!

**Comment by DrewsCodeLife** [comment]
Hi @Lisias !

I'm having the same issue, I looked through the log and double checked my files, I don't think it solved my problem. Log is attached, thanks for your hel
[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/7575378/KSP.log)
p!

**Comment by Lisias** [comment]
JESUS CHRIST, I BORKED THE DISTRIBUTION!

**Comment by Lisias** [comment]
> Hi @Lisias !
> 
> I'm having the same issue, I looked through the log and double checked my files, I don't think it solved my problem. Log is attached, thanks for your hel [KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/7575378/KSP.log) p!

Hi! I did a peek on the log and nope, you don't have exactly the same issue. You have a new problem that happened to trigger the same misbehaviour from KSP, that leads TweakScale to wrongly think there's something wrong with itself. 

I found something interesting on your KSP:

```
KSPAPIExtensions v1.7.5.0
KSPe.Light.TweakScale v2.4.1.6
Scale v2.4.6.3
```

The KSPApiExtensions should not be available on your rig, much less from inside TweakScale!

```
[LOG 13:03:13.777] Load(Assembly): TweakScale/Plugins/KSPAPIExtensions
```

Hummm…. I had a hunch, and dug my TweakScale archive for every TweakScale version ever released and found that, indeed, KSPAPIExtensions was distributed with TweakScale up to v1.7 in… 2014!! :)

So, or you are a old school die hard KSP player that is maintaining your KSP installment working since the old times (kudos!!!), or perhaps you did downloaded an old version by accident and ended up with the KSPApiExtensions lingering dormant.

In a way or another, it's something on this old version of KSPAPIExtensions that are borking the KSP's flawed `Assembly Loader/Resolver` (that, by itself, induces everybody else to bork, TweakScale being one of them):

```
[LOG 13:03:16.619] [UIPartActionsExtendedRegistration] Elected unopposed version= 1.7.5.0 at C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\TweakScale\Plugins\KSPAPIExtensions.dll
[EXC 13:03:16.625] MissingMethodException: void PopupDialog.SpawnPopupDialog(string,string,string,bool,UnityEngine.GUISkin)
        UnityEngine.DebugLogHandler:LogException(Exception, Object)
        ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
        UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```
By removing `GameData/TweakScale/Plugins/KSPAPIExtensions.dll` from your rig, this exception will not happen, and so the KSP's flawed Assembly Loader/Resolver will not be triggered, and so TweakScale will not have the carpet pulled under its feet. :) 

Congrats, dude, this a new! It's the first time I diagnosed something related to an ancient release of TweakScale!! :)

Cheers!

**Comment by DrewsCodeLife** [comment]
Wow! Thank you so much for taking time out of your day to help me, and even more so for the well formulated response!

I have been playing KSP for a long time (probably since 2013-2014) and up until recently I have refused to update because BDArmory is the best IMO. Recently I saw a video and knew I had to get back to it. **I did make a fatal flaw though, I didn't double check that all my old files were deleted prior to installing mods**. This could easily be the issue here.

I went ahead and deleted it like you mentioned, I'm still having the same error, but with a different log message now.

I'm getting the following errors right after a stack trace, and right before TweakScale throws the error message, does this tell you anything? I looked for the referenced file but couldn't find it.

`[ERR 15:14:29.293] Unable to use a named GUIStyle without a current skin. Most likely you need to move your GUIStyle initialization code to OnGUI

[ERR 15:14:29.295] Unable to use a named GUIStyle without a current skin. Most likely you need to move your GUIStyle initialization code to OnGUI`

Should I go ahead and delete everything and start fresh? I don't want to waste your time if I can easily fix it on my end :)

Thanks again for your help! Updated log file attached
[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/7575502/KSP.log)

**Comment by Lisias** [comment]
> I have been playing KSP for a long time (probably since 2013-2014) and up until recently I have refused to update because BDArmory is the best IMO. Recently I saw a video and knew I had to get back to it. **I did make a fatal flaw though, I didn't double check that all my old files were deleted prior to installing mods**. This could easily be the issue here.

Dude, I'm going back to 1.4.3…. I stop updating on 1.7.3, but with all the problems I'm getting with Serenity, I don't have a compelling reason to stick with it neither.. :P 

I understand you perfectly… :D 


> I'm getting the following errors right after a stack trace, and right before TweakScale throws the error message, does this tell you anything? I looked for the referenced file but couldn't find it.
> 
> `[ERR 15:14:29.293] Unable to use a named GUIStyle without a current skin. Most likely you need to move your GUIStyle initialization code to OnGUI
> 
> [ERR 15:14:29.295] Unable to use a named GUIStyle without a current skin. Most likely you need to move your GUIStyle initialization code to OnGUI`

These ones are annoying, but they are "safe". It's something I really should tackle down, but since they are harmless they are always in the end point of my back log…. I really need more time for modding….


> Should I go ahead and delete everything and start fresh? I don't want to waste your time if I can easily fix it on my end :)

Not yet. Let me check this new log first - you are not wasting my time, because whatever is biting you will bite more people in the wild, and I need to be aware of it. :) 

I will post something with the results in the next few hours, I just downloaded the new KSP.log.

**Comment by DrewsCodeLife** [comment]
Umm. Shit... This is awkward lol

So I may have grown impatient and fresh installed, it booted up without any fatal errors.

It could have to do with the fact I used curseforge before as well, I stopped playing a while ago and didn't even know CKAN was a thing hahaha.

If you need anything else from me to assist in your investigation let me know!

**Comment by Lisias** [comment]
@DrewsCodeLife , **now** I'm worried. :(

I found this as the first Reflection Exception on your KSP.log, and this one is on me, indeed:

```
[LOG 15:14:29.291] [TweakScale] ERROR: System.TypeInitializationException: The type initializer for 'KSPe.IO.Hierarchy`1' threw an exception. ---> System.TypeInit
ializationException: The type initializer for 'KSPe.IO.Hierarchy' threw an exception. ---> System.ComponentModel.Win32Exception: The system cannot find the file s
pecified.

  at KSPe.Multiplatform.LowLevelTools.Windows32.GetFinalPathName (System.String path) [0x0002b] in <f267864bc5b14efd9db6b3cdd8146f53>:0
  at KSPe.Multiplatform.FileSystem.Reparse_windows (System.String path) [0x00000] in <f267864bc5b14efd9db6b3cdd8146f53>:0
  at KSPe.Multiplatform.FileSystem.ReparsePath (System.String path) [0x00015] in <f267864bc5b14efd9db6b3cdd8146f53>:0
  at KSPe.IO.Directory.RealPath (System.String path) [0x0001f] in <f267864bc5b14efd9db6b3cdd8146f53>:0
  at KSPe.IO.Directory.Exists (System.String path) [0x00000] in <f267864bc5b14efd9db6b3cdd8146f53>:0
  at KSPe.IO.Path.EnsureTrailingSeparatorOnDir (System.String path, System.Boolean blindlyAppend) [0x00033] in <f267864bc5b14efd9db6b3cdd8146f53>:0
  at KSPe.IO.Path.Combine (System.String path1, System.String path2) [0x00007] in <f267864bc5b14efd9db6b3cdd8146f53>:0
  at KSPe.IO.Hierarchy..ctor (System.String name, System.String dirName) [0x0000d] in <f267864bc5b14efd9db6b3cdd8146f53>:0
  at KSPe.IO.Hierarchy..cctor () [0x0002d] in <f267864bc5b14efd9db6b3cdd8146f53>:0
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at KSPe.Util.SystemTools+Assembly+Loader`1[T].TryPath (System.String path, System.String[] subdirs) [0x00000] in <f267864bc5b14efd9db6b3cdd8146f53>:0
  at KSPe.Util.SystemTools+Assembly+Loader`1[T]..ctor (System.String[] subdirs) [0x0002e] in <f267864bc5b14efd9db6b3cdd8146f53>:0
  at TweakScale.Startup.Start () [0x00018] in <45182d9103c649a9b01afeb7178d397a>:0  at error:0
```

Apparently something changed drastically on Windows 10 recently, because I don't have any report of this error - and TweakScale is used a lot.


> Umm. Shit... This is awkward lol

A lot…. :P

> So I may have grown impatient and fresh installed, it booted up without any fatal errors.

What TweakScale (if any) are you using now?

 
> If you need anything else from me to assist in your investigation let me know!

yes I will, I don't have a Windows 10 machine at hand to make tests. I will need your help on this.

Can you please check if there's a file named "kernal.dll" on your Windows/Wow64/ dir? Or in somewhere else? I think this is the DLL that it's missing.

**Comment by DrewsCodeLife** [comment]
2.4.6.2 is the most recent update in my change log.md file, and no way in hell I could skip on it, the freedom tweakscale allows is irreplacable.

Couldn't find Windows/Wow64, but I did have SysWOW64, and nothing came up :p

**Comment by Lisias** [comment]
> 2.4.6.2 is the most recent update in my change log.md file, and no way in hell I could skip on it, the freedom tweakscale allows is irreplacable.
> 
> Couldn't find Windows/Wow64, but I did have SysWOW64, and nothing came up :p

So you found the problem for me! `kernel32.dll is not more!!!! #DAMN

Let's do something: you **can** update to 2.4.6.3 as long you don't update KSPe.Light.TweakScale - this is the that it's borking on you.

In the mean time, you may want to "fix" your Windows, because as far as I know, the kernel32.dll is still needed for running 32 bits applications (and there's still a lot yet).  I dug out, and I found that the following commands **may** fix the problem for you:

```
sfc /scannow [Enter] 
DISM.exe /Online /Cleanup-image /Restorehealth [Enter]
```

You wlll need to run these ones on the command line of an Administrator user: Press Start > Windows System > Command Prompt right-click run as admin

Additionally, I also found that `regsvr32.exe /i Kernel32.dll` will re-register the DLL into System Registry if it is available.

Do what you do, **DO NOT** download **ANYTHING** claiming will fix this one for you.

**Comment by Lisias** [comment]
Ini time @DrewsCodeLife , it happens I have a Brave Wallet. :)

0x8D62172c0fe0Ad190dEE284c5E4352e221c9050c

**Comment by DrewsCodeLife** [comment]
> Ini time @DrewsCodeLife , it happens I have a Brave Wallet. :)

Well this is awkward, again. I guess my Uphold wallet is under review? I'll set a reminder to come back and tip you lol.

And thank you! I'll keep that in mind. Glad we could work it out 🥂

**Comment by DrewsCodeLife** [comment]
Hey @Lisias !

So I worked through Upholds verification process, got my account reviewed, and went to transfer the coins when I noticed the gas fee....

> Network withdrawal fee: 28.09094 BAT ≈ $ 30.76

**What the shit??**

I was going to tip $5-$10 so no way in hell I'm spending $30 to tip you. You gotta venmo or something I can send it to? Already promised you that tip, I wanna make good on that promise :)

**Comment by Lisias** [comment]
> Hey @Lisias !
> 
> So I worked through Upholds verification process, got my account reviewed, and went to transfer the coins when I noticed the gas fee....
> 
> > Network withdrawal fee: 28.09094 BAT ≈ $ 30.76
> 
> **What the shit??**
> 
> I was going to tip $5-$10 so no way in hell I'm spending $30 to tip you. You gotta venmo or something I can send it to? Already promised you that tip, I wanna make good on that promise :)

Whatahell? 30 bucks for the transfer? o.O

How about paypal or patreon? I don't have a venmo (never heard of it), I'm checking about it.

**Comment by Lisias** [comment]
Closing this, as the problem was fixed and I forgot about it. :)
