### ISSUE TITLE
The type initializer threw an exception.

### ISSUE THREAD

**Issue by Joey-Destroyah** [net-lisias-ksp/TweakScale#206]
![image](https://user-images.githubusercontent.com/62820134/138365953-449add23-52cf-4c5a-8d66-e7ff26db728d.png)
Mods
![image](https://user-images.githubusercontent.com/62820134/138366040-65dd3695-aeda-4887-a3fd-8a1bbd27dd4f.png)
Ksp version 1.10.1

**Comment by Lisias** [comment]
Hi, @JovietUnion .

Without the KSP.log, I can only guess. Please provide the KSP.log so I can inspect exactly what's going on.

This error usually happens **when another add'on** borks, what ends up with the System.Reflection data structures inconsistent, and from that point everything that relies on it borks relentlessly - as TweakScale.

Without the KSP.log, I can't tell you who is borking on Reflection in order to have it fixed.

**Comment by KSPFreak** [comment]
hmm... i did not install any Pre-release stuff (at not on purpose)...all the mods i use i install via CKAN. Imma reach out the wild blue guy, maybe he has something for me.  But thanks for the help, appreciate it :)
