### ISSUE TITLE
"missing class: the type of initializer for KSPe.IO.hierarchy'1' threw an exception".

### ISSUE THREAD

**Issue by Elmergas124** [net-lisias-ksp/TweakScale#210]
Hi, i have a problem, when i open KSP, an error message appears that say that "tweak scale cant work properly without support DLLs" and that "missing class: the type of initializer for KSPe.IO.hierarchy'1' threw an exception". I dont know what that means and I already reinstalled tweakscale, it didn't work. please help.
[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/7530882/KSP.log)
@Lisias

**Comment by Lisias** [comment]
Hi, @Elmergas124 ! I got it.

This is what's happening:

```
[ERR 21:48:24.025] AssemblyLoader: Exception loading 'InterstellarFuelSwitch': System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was
thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0
  at AssemblyLoader.LoadAssemblies () [0x000e6] in <cd473063d3a2482f8d93d388d0c95035>:0
```

and 

```
[ERR 21:48:24.044] AssemblyLoader: Exception loading 'PhotonSail': System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0
  at AssemblyLoader.LoadAssemblies () [0x000e6] in <cd473063d3a2482f8d93d388d0c95035>:0

Additional information about this exception:

 System.IO.FileNotFoundException: Could not load file or assembly 'Interstellar_Redist, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Interstellar_Redist, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'
```

and finally:

```
[ERR 21:48:24.049] ADDON BINDER: Cannot resolve assembly: ContractConfigurator, Culture=neutral, PublicKeyToken=null

[ERR 21:48:24.050] AssemblyLoader: Exception loading 'ScrapYard_ContractConfigurator': System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadExcepti
on' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0
  at AssemblyLoader.LoadAssemblies () [0x000e6] in <cd473063d3a2482f8d93d388d0c95035>:0

Additional information about this exception:

 System.IO.FileNotFoundException: Could not load file or assembly 'ContractConfigurator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'ContractConfigurator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
```

The first two problems can be solved by installing [this file](https://github.com/sswelm/KSP-Interstellar-Extended/blob/master/GameData/999_Scale_Redist.dll) and [this file](https://github.com/sswelm/KSP-Interstellar-Extended/blob/master/GameData/Interstellar_Redist.dll) into your GameData . You probably forgot to install these two files if you did a manual install, but if you are using CurseInstaller, there's a limitation on it that doesn't allows installation of files into GameData - but since these files never changes, at least you need to do it only once.

The third problem is about Scrap Yard integration to Contract Configurator that you have installed, but forgot to install Contract Configurator. Install Contract Configurator and this last problem will be solved.

Additionally, there's a tool embedded with KSP Intestellar that it's pretty useful, Module Manager WatchDog, that would had helped you diagnosing the first two problems - but it needs [this another file](https://github.com/sswelm/KSP-Interstellar-Extended/blob/master/GameData/666_ModuleManagerWatchDog.dll) on GameData too - and I think I found a weakness on this tool that I need to tackle down somehow.

**Comment by Lisias** [comment]
let me know when your rig is fixed, so I can close this! 

Cheers!

**Comment by Elmergas124** [comment]
Thanks you so much, now i can play ksp again. hope you have a wonderful day :)
@Lisias
