### ISSUE TITLE
Missing DLL "KSPe.IO.Hierarchy\1" also stuck on loading BG expansion/Serenity

### ISSUE THREAD

**Issue by atllok-nor** [net-lisias-ksp/TweakScale#230]
Hi, just downgraded to 1.10 on a clean install to play with RO. Any ideas? I saw on a previous release you mentioned the missing DLL, but I did not understand how you wanted us to fix it or workaround it... @Lisias
[Playerlog.zip](https://github.com/net-lisias-ksp/TweakScale/files/7855592/Playerlog.zip)

Had to attach player.log to zip in order to upload

**Comment by atllok-nor** [comment]
After having a good look through the .log I noticed a broken DLL of a mod I have not installed, which is not available through CKAN. I have no idea how that DLL file was around, as I made sure to completely wipe the folder and reinstall 1.10... I might have gotten that DLL from a modpack, but it should not have been there. 

However, removing this DLL did remove the "KSPe.IO.Hierarchy..." exception I received, and it is no longer stuck on Serenity? Seems weird that the DLL from that mod would give Tweakscale this error? Closing the issue, but leaving it here in-case anyone else has a similar problem. Read your .log my guys :)

**Comment by Lisias** [comment]
Hi, @atllok-nor .

What happened is that a well known bug from KSP >= 1.8 has bitten you.

There's a serious flaw in a thingy called "Assembly Resolver/Loader" that once is triggered, **every single DLL** trying to be loaded after throws an exception, just like you found.

What triggers this bug is trying to loading a dependency that it's not there (or it's faulty, as having another dependency, and this is is borked while loading).

It's a pain in the ass, and a very serious problem that should had been fixed by Squad on KSP 1.8.1 at least. However…

(sigh)

There's no easy way out other than making sure every DLL is being loaded correctly - be by installing the missing dependencies, be by removing the Add'On that is borking due it as you did.

Cheers!
