### ISSUE TITLE
TweakScale is being summoned to scale parts without TweakScale module info??

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/TweakScale#41]
Apparently TweakScale is being called to scale parts that doesn't have a TweakScale Module info!

```
[ERR 02:01:20.033] Cannot find module 'TweakScale' (-699235618)

[ERR 02:01:20.033] Module TweakScale threw during OnStart: System.NullReferenceException: Object reference not set to an instance of an object
  at TweakScale.TweakScale.Setup () [0x00000] in <filename unknown>:0 
  at TweakScale.TweakScale.OnStart (StartState state) [0x00000] in <filename unknown>:0 
  at Part.ModulesOnStart () [0x00000] in <filename unknown>:0 
```

See the following links for details:
https://forum.kerbalspaceprogram.com/index.php?/topic/122020-16x-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v152-бруно-8feb2019/&do=findComment&comment=3593056

[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/3144942/KSP-12.log)

**Comment by ncanceill** [comment]
Maybe this is not the exact same issue but it is surely related, probably the relevant part of the code is not robust enough

I am seeing this exception in Editor (VAB/SPH) with three specific parts: [SXTfloatFront](https://github.com/linuxgurugamer/SXTContinued/blob/master/GameData/SXT/Parts/CoreTech/Utility/floats/part.cfg), [SXTfloatMid](https://github.com/linuxgurugamer/SXTContinued/blob/master/GameData/SXT/Parts/CoreTech/Utility/floats/partMid.cfg) and [SXTfloatOutboard](https://github.com/linuxgurugamer/SXTContinued/blob/master/GameData/SXT/Parts/CoreTech/Utility/floats/partOutboard.cfg)

These parts actually do have a TweakScale module, patched in [here](https://github.com/linuxgurugamer/SXTContinued/blob/master/GameData/SXT/Patches/ModCompatibility/SXT_TweakScale.cfg#L1110-L1116), however it behaves weirdly:
- As soon as the part is picked up in the Editor's part list, it triggers exceptions as mentioned by @Lisias above
- Instead of showing a default scale of "100%" (as `type = free` should imply) in the PAW, the TweakScale gauge shows a default scale of "2"
- Clicking the gauge or the arrow buttons to change the scale will irreversibly make the part extremely small (only a few pixels wide)
- Using a ModuleManager file to try to rewrite the TweakScale module will still trigger the exception and the PAW will have an additional TweakScale gauge showing a scale of "Default" on which clicking has no effect, here is the patch I tried:
```
@PART[SXTfloat*]:AFTER[SXT]:NEEDS[TweakScale]
{
	%MODULE[TweakScale]
	{
            %type = free
	}
}
```

- Saving the vessel, the craft file shows that the TweakScale module indeed exists:
```
	MODULE
	{
		name = TweakScale
		isEnabled = True
		currentScale = 100
		defaultScale = 100
		defaultTransformScale = (0, 0, 0)
		DryCost = 0
		stagingEnabled = True
		EVENTS
		{
		}
		ACTIONS
		{
		}
		UPGRADESAPPLIED
		{
		}
	}
```

**Comment by ncanceill** [comment]
Thanks for the new update, this show more clearly that my issue is only vaguely related and seems to be part of a broader problem

I have issues with a few other SXT parts, the common behavior being:
- NullRefs in `TweakScale.TweakScale.Setup` from `OnStart` or `Onload` because TweakScale module is not found
- Two gauges in PAW: a responsive one and a non-responsive one
- The non-responsive gauge displays "Default"
- NullRefs in `TweakScale.TSGenericUpdater.OnRescale` when using the responsive gauge
- The responsive gauge switches between two numbers, either 1 and 2 or 2 and 4
- The corresponding scales are roughly either 1:1 and 2:1, 1:2.2 and 1:1.1, or 1:20 and 1:10

I also have the same issue with one B9 Aerospace HX part (and only one, which I do not even use)

All of these parts are detected having duplicated properties when the main menu is loaded and TweakScale runs the sanity check

I am confused about how duplicated modules can persist and how to track down the source of my issues (of course I refreshed ModuleManager cache), whether it is a conflicting patch from another mod or something else. @Lisias could you please point me to some more info on this Kraken food?

Cheers.

**Comment by Lisias** [comment]
Well, now that I'm on a computer, I can comment it.

What happens is that any part that fails the Sanity Check have TweakScale support withdrawn programmatically on the startup. This is intended to prevent you from running into game crashes and some other disasters.

So, even by Module Manager injecting the TweakScale support on the part, if TweakScale detects a failure on the Sanity Check, the patch is "unpatched".

However…

There're Racing Conditions on the Startup where more than one Add'On compete for the GameDatabase concurrently, and this is borking TweakScale heavily. This is (being attempt to) handled on the #31 issue.

Worse, most of the time, the part being affected are not patched by TweakScale default patches or by the Add'On maintainer, but it's usually a thirdy party patch that goes rogue by blindly patching what'd already patched, or patching it wrongly, This make things very hard to diagnose, as one need to reproduce precisely the running environment to confirm the problem, and then remove Add'Ons one by one to detect exactly the Add'Ons involved (always more than one, sometimes more than 2 - and only one has the rogue patch).

So, in the aftermath, we have essentially a Kraken Feast here. A lot of problems happening concurrently.

Right now I'm (trying) to fire up a KSP 1.7 installment of mine with 145 Add'Ons (including the ones borking up in your log) to see what happens. I hope to reproduce the problem on this installment, as I know it very well and have a lot of control on it. If everything works fine on it, I will try to reproduce exactly your installment and redo the tests.

I'll come back to you as soon as possible.

**Comment by ncanceill** [comment]
Thank you for explaining this and also tracking the SXT problems down in the forums!

Apparently all my issues were actually related to #49 so I will continue discussing them there

**Comment by Lisias** [comment]
I think I'm understanding the problem now. From this [post](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-14-tweakscale-under-lisias-management-2430-2019-0608/&do=findComment&comment=3619597), I realized that it's again some conflict between craft data and prefab data.

```
[ERR 17:34:14.103] Cannot find module 'TweakScale' (-699235618)

[ERR 17:34:14.103] Module TweakScale threw during OnStart: System.NullReferenceException: Object reference not set to an instance of an object
  at TweakScale.TweakScale.Setup () [0x00000] in <filename unknown>:0 
  at TweakScale.TweakScale.OnStart (StartState state) [0x00000] in <filename unknown>:0 
  at Part.ModulesOnStart () [0x00000] in <filename unknown>:0 
[LOG 17:34:15.386] Tube2 added to ship - part count: 4

[ERR 17:35:51.974] Cannot find module 'TweakScale' (-699235618)
[ERR 17:35:51.975] Module TweakScale threw during OnStart: System.NullReferenceException: Object reference not set to an instance of an object
  at TweakScale.TweakScale.Setup () [0x00000] in <filename unknown>:0 
  at TweakScale.TweakScale.OnStart (StartState state) [0x00000] in <filename unknown>:0 
  at Part.ModulesOnStart () [0x00000] in <filename unknown>:0 

[LOG 17:35:53.383] EnginePlate3 added to ship - part count: 5
```

**Comment by Lisias** [comment]
Well.. As time passed by, a lot of issues (perhaps related) ended up fixing this one by colateral effect.

The related issues are:

* #114 KSP 1.8 (and 1.9) rendered the Sanity Checks useless
* #110 Revert to Vehicle Assembly and Loading Craft are mangling the part attachments.
* #30 Prevent incorrectly initialized Modules to be used 

With the fixes applied for the above mentioned issues, I don't think this issue is possible anymore. So I'm closing it.

**Comment by Lisias** [comment]
* Issue #125 is also a good candidate to a related issue!
