### ISSUE TITLE
Check the Default patches for problems due wildcard!

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/TweakScale#49]
Default TweakScale patches are using WildCards unsafely. At least the Mark IV one is being caught by #34.

This is somewhat urgent.

**Comment by ncanceill** [comment]
Hi again @Lisias!

---

I caught one in [B9_HX.cfg](https://github.com/net-lisias-ksp/TweakScale/blob/master/GameData/TweakScale/patches/B9_Aerospace/B9_HX.cfg#L125-L140)

The patch for `B9_Structure_HX1_S_H*` matches `B9_Structure_HX1_S_HS` which is patched again right below, and should therefore be removed

---

The other problems I had came from interaction between [MarkIVSystem_TweakScale.cfg](https://github.com/net-lisias-ksp/TweakScale/blob/master/GameData/TweakScale/patches/MarkIVSystem_TweakScale.cfg) and SXT, which should be fixed by [your PR](https://github.com/linuxgurugamer/SXTContinued/pull/71) (except that you missed some, I will comment in the PR)

---

Anyway, I believe the safe path is to prepend `%` to all TweakScale module properties in the patches

Granted, it will silence conflicts but they should not occur frenquently and, when they do, it is likely that the conflicting patches will be similar if not identical because they apply to the same part. In the worst case, an inappropriate `type` or `defaultScale` will be applied last and override the appropriate value so the part will not scale appropriately, but this could be easily solved by checking the ModuleManager log to find out the offending patches

**Comment by Lisias** [comment]
B9 patches reviewed and fixed. Thanks, @ncanceill !

**Comment by Lisias** [comment]
Detected issues solved. A lot of wildcards was left behind, but none of them triggered problems for the Add'Ons I managed to find.

Some patches should be considered deprecated as the Add'Ons apparently are not available anymore, but this is something for another issue.

Closing as fixed.
