### ISSUE TITLE
Support for all parts

### ISSUE THREAD

**Issue by Monniasza** [net-lisias-ksp/TweakScale#78]
Please add ability to scale all parts using only supported modules.
Ability to use TweakScale with all parts will make most scaling definitions obsolete.

Auto-detect parts:
With stack nodes: use stack scaling
Radial only: use free scaling

**Comment by Lisias** [comment]
What you ask is not feasible. Each part can have different characteristics, and they need to be tacked down individually. Things appears to be easy to patch because a lot of =TWEAKSCALEEXPONENTS and TWEAKSCALEBEHAVIOURS were created to make things easy - but make no mistake, things are not that easy under the bonnet.

You still need to look inside the part to see what behaviour or exponent you will need for it.

There's an effort to create a simplified scaling model for people that would not mind losing some fidelity in exchange for a way simpler scaling model, the Add'On [All Tweak](https://forum.kerbalspaceprogram.com/index.php?/topic/182700-14x-17x-all-tweak-06-august-3rd-2019/). That guy is aiming to do what you want, a and you can help him on this by giving him ideas on how to proceed.

I'm collaborating with him when things blow up (and things blow up!) anyway, I just don't want to do it on the canon TweakScale due the extreme breakage this would cause on crafts and savegames that relies on canon. Not to mention that there're good reasons to keep canon TweakScale using scales as we have nowadays.

**Comment by Lisias** [comment]
Since the user didn't gave feedback, and since we already have an Add'On aiming to do what it's proposed, I'm closing this.
