### ISSUE TITLE
Syntax error in version file for 2.4.3.8

### ISSUE THREAD

**Issue by HebaruSan** [net-lisias-ksp/TweakScale#81]
The download for 2.4.3.8 contains this metadata:

```json
{
	"NAME"		: "TweakScale",
	"URL"		: "https://github.com/net-lisias-ksp/TweakScale/blob/master/TweakScale.version",
	"DOWNLOAD"	: "https://github.com/net-lisias-ksp/TweakScale/releases",
	"CHANGE_LOG"	: "https://raw.githubusercontent.com/net-lisias-ksp/TweakScale/CHANGE_LOG.md",
	"CHANGE_LOG_URL": "https://raw.githubusercontent.com/net-lisias-ksp/TweakScale/CHANGES.md",
	"VERSION":{
		"MAJOR":2,
		"MINOR":4,
		"PATCH":3,
		"BUILD":8
		},
	"KSP_VERSION_MIN":{
		"MAJOR":1,
		"MINOR":4,
		"PATCH":1
		}
	"KSP_VERSION_MAX":{
		"MAJOR":1,
		"MINOR":7,
		"PATCH":99
		}
}
```

There's a missing comma between `KSP_VERSION_MIN` and `KSP_VERSION_MAX`. This is preventing this release from being listed in CKAN.

Unfortunately I can't submit a pull request to fix this because this data is not yet reflected on GitHub:

https://github.com/net-lisias-ksp/TweakScale/blob/master/TweakScale.version

**Comment by Lisias** [comment]
God damned typo, missing a comma. :(.

Fixing it.

**Comment by Lisias** [comment]
That caught with my pants down. It's no doubt, there's a typo on the file.

![Screen Shot 2019-10-23 at 11 13 03](https://user-images.githubusercontent.com/64334/67396565-35466100-f57e-11e9-9fe9-16953d756622.png)

But that passed through because KSP-AVC gladly accepted that file, with or without a typo. And I relied on it when testing this thing.

```
[LOG 11:18:20.828] KSP-AVC -> /Users/lisias/Workspaces/KSP/runtime/1.8.0/GameData/TweakScale/TweakScale.version
        NAME: TweakScale
        URL: https://raw.githubusercontent.com/net-lisias-ksp/TweakScale/master/TweakScale.version
        DOWNLOAD: https://github.com/net-lisias-ksp/TweakScale/releases
        GITHUB: NULL
        DISALLOW_VERSION_OVERRIDE: False
        VERSION: 2.4.3.8
        KSP_VERSION: Any
        KSP_VERSION_MIN: 1.4.1
        KSP_VERSION_MAX: 1.7.99
        CompatibleKspVersion: True
        CompatibleKspVersionMin: True
        CompatibleKspVersionMax: False
        CompatibleGitHubVersion: True
```

Well, now I know. With KSP-AVC using the file as is, I don't need to fix the distribution and upload everything again on SpaceDock and CurseForge - but I think AVC should at least also kick my balls by allowing a typo on that file while recovering from the parsing error.

And the thing is fixed now. I will close this issue when the master will be pointing the dev branch, were I'm testing things manually this time.

![Screen Shot 2019-10-23 at 11 13 24](https://user-images.githubusercontent.com/64334/67396986-ea791900-f57e-11e9-946e-0abd33887c2b.png)

**Comment by Lisias** [comment]
master is not pinpoint a updated and correct version file.

I'm sorry for the trouble, I will get better compliance tools on my chain.
